<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GGCLQ1N" failures="1" tests="4" name="ui.ReportsTest" time="1.626" errors="0" timestamp="2022-10-04T20:38:24 SGT" skipped="0">
  <testcase classname="ui.ReportsTest" name="reportTest3" time="0.002"/>
  <system-out>
    <![CDATA[Test Name is - reportTest3
This is Test 3.
Status of Test is Success]]>
  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest1" time="1.620">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at ui.ReportsTest.reportTest1(ReportsTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- reportTest1 -->
  <system-out>
    <![CDATA[Test Name is - reportTest1
This is Test 1.
Test failed - screenshot captured. 
<a href="C:\Users\shank\eclipse-workspace\seleniumTesting\screenshot\Tue-Oct-04-20-38-23-SGT-2022.png">Test Results</a>]]>
  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest4" time="0.002"/>
  <system-out>
    <![CDATA[Test Name is - reportTest4
Status of Test is Success]]>
  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest2" time="0.002"/>
  <system-out>
    <![CDATA[Test Name is - reportTest2
This is Test 2.
Status of Test is Success]]>
  </system-out>
</testsuite> <!-- ui.ReportsTest -->
